### ISSUE TITLE
Classes not being minified.

### ISSUE THREAD

**Issue by akshitkrnagpal** [stldo/gatsby-plugin-minify-classnames#1]
Hi

I have a gatsby project with tailwind integration using postcss. I installed this plugin and added this to my project (after postcss plugin) and tried production and development build. There was no change.

After taking a look I managed to make `css` by changing your loop and adding `modules: true` to options.

```js
for (let { oneOf } of rules) {
    for (let { use } of oneOf) {
      if (!use) continue
      for (let { options } of use) {
        if (!options || !options.localIdentName) continue
        
        options.modules = true; // Here

        options.getLocalIdent = (context, _, localName) => {
          const path = context.resourcePath
          const minified = getMinifiedIdentifier({ path, localName }, dictionary)
          console.log(localName, minified);
          return minified
        }
      }
    }
```

After this change css were correctly minified.

But my HTML still shows old classes. **Is there any additional config required?**

BTW. Thanks for your work on this. 😄

**Comment by stldo** [comment]
Hi! This plugin works with CSS Modules, it just adds `getLocalIdent` option to the original webpack configuration, thus minifying local idents, i.e. `:local` class names. If you are following Gatsby official Tailwind guide, you must be importing the class names into the `:global` scope in `gatsby-browser.js` with something like `import 'tailwindcss/dist/base.min.css'`. This should be the reason of nothing being minified. I don't know exactly how Tailwind works, but from what I read about, a workaround could be to create a local css module, import Tailwind classes using `@tailwind base`, `@tailwind components`, etc., and then import this module in the js — `import styles from './local.module.css'`. This way you could use Tailwind class names as local idents, e.g. ``className={`${styles['bg-blue-500']} ${styles['text-white']}`}``.
