### ISSUE TITLE
Plugin does not work on windows due to hardcoded forward slash check

### ISSUE THREAD

**Issue by manvydasu** [stldo/gatsby-plugin-minify-classnames#7]
Plugin uses this logic for detecting css-loader

```
...
if (!loader?.includes('/css-loader/') || !options?.modules) {
          continue
}
...
```

Problem is that OS Windows use backward slash for it's path, i.e. 

`C:\gatsby-demo\node_modules\css-loader\dist\cjs.js`

As a result, condition mentioned above never results in false and the plugin does not do it's job.

**Comment by stldo** [comment]
Hi @manvydasu , thanks for reporting this issue. I've published a new version on npm fixing it, could you please test it and confirm if it's working fine?

**Comment by stldo** [comment]
Hey @manvydasu, did you test the update? Please let me know if it's woking as expected, so I can close this issue.

**Comment by manvydasu** [comment]
@stldo 
Sorry for not getting back earlier.

Yes it does work. Thanks for the fix.
